// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"tellmeac/extended-schedule/adapters/ent/studygroup"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StudyGroupCreate is the builder for creating a StudyGroup entity.
type StudyGroupCreate struct {
	config
	mutation *StudyGroupMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (sgc *StudyGroupCreate) SetName(s string) *StudyGroupCreate {
	sgc.mutation.SetName(s)
	return sgc
}

// SetFacultyName sets the "facultyName" field.
func (sgc *StudyGroupCreate) SetFacultyName(s string) *StudyGroupCreate {
	sgc.mutation.SetFacultyName(s)
	return sgc
}

// SetID sets the "id" field.
func (sgc *StudyGroupCreate) SetID(s string) *StudyGroupCreate {
	sgc.mutation.SetID(s)
	return sgc
}

// Mutation returns the StudyGroupMutation object of the builder.
func (sgc *StudyGroupCreate) Mutation() *StudyGroupMutation {
	return sgc.mutation
}

// Save creates the StudyGroup in the database.
func (sgc *StudyGroupCreate) Save(ctx context.Context) (*StudyGroup, error) {
	var (
		err  error
		node *StudyGroup
	)
	if len(sgc.hooks) == 0 {
		if err = sgc.check(); err != nil {
			return nil, err
		}
		node, err = sgc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StudyGroupMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = sgc.check(); err != nil {
				return nil, err
			}
			sgc.mutation = mutation
			if node, err = sgc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(sgc.hooks) - 1; i >= 0; i-- {
			if sgc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = sgc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, sgc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*StudyGroup)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from StudyGroupMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (sgc *StudyGroupCreate) SaveX(ctx context.Context) *StudyGroup {
	v, err := sgc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sgc *StudyGroupCreate) Exec(ctx context.Context) error {
	_, err := sgc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sgc *StudyGroupCreate) ExecX(ctx context.Context) {
	if err := sgc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sgc *StudyGroupCreate) check() error {
	if _, ok := sgc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "StudyGroup.name"`)}
	}
	if _, ok := sgc.mutation.FacultyName(); !ok {
		return &ValidationError{Name: "facultyName", err: errors.New(`ent: missing required field "StudyGroup.facultyName"`)}
	}
	return nil
}

func (sgc *StudyGroupCreate) sqlSave(ctx context.Context) (*StudyGroup, error) {
	_node, _spec := sgc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sgc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected StudyGroup.ID type: %T", _spec.ID.Value)
		}
	}
	return _node, nil
}

func (sgc *StudyGroupCreate) createSpec() (*StudyGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &StudyGroup{config: sgc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: studygroup.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: studygroup.FieldID,
			},
		}
	)
	_spec.OnConflict = sgc.conflict
	if id, ok := sgc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := sgc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: studygroup.FieldName,
		})
		_node.Name = value
	}
	if value, ok := sgc.mutation.FacultyName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: studygroup.FieldFacultyName,
		})
		_node.FacultyName = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.StudyGroup.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.StudyGroupUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (sgc *StudyGroupCreate) OnConflict(opts ...sql.ConflictOption) *StudyGroupUpsertOne {
	sgc.conflict = opts
	return &StudyGroupUpsertOne{
		create: sgc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.StudyGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (sgc *StudyGroupCreate) OnConflictColumns(columns ...string) *StudyGroupUpsertOne {
	sgc.conflict = append(sgc.conflict, sql.ConflictColumns(columns...))
	return &StudyGroupUpsertOne{
		create: sgc,
	}
}

type (
	// StudyGroupUpsertOne is the builder for "upsert"-ing
	//  one StudyGroup node.
	StudyGroupUpsertOne struct {
		create *StudyGroupCreate
	}

	// StudyGroupUpsert is the "OnConflict" setter.
	StudyGroupUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *StudyGroupUpsert) SetName(v string) *StudyGroupUpsert {
	u.Set(studygroup.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *StudyGroupUpsert) UpdateName() *StudyGroupUpsert {
	u.SetExcluded(studygroup.FieldName)
	return u
}

// SetFacultyName sets the "facultyName" field.
func (u *StudyGroupUpsert) SetFacultyName(v string) *StudyGroupUpsert {
	u.Set(studygroup.FieldFacultyName, v)
	return u
}

// UpdateFacultyName sets the "facultyName" field to the value that was provided on create.
func (u *StudyGroupUpsert) UpdateFacultyName() *StudyGroupUpsert {
	u.SetExcluded(studygroup.FieldFacultyName)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.StudyGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(studygroup.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *StudyGroupUpsertOne) UpdateNewValues() *StudyGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(studygroup.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.StudyGroup.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *StudyGroupUpsertOne) Ignore() *StudyGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *StudyGroupUpsertOne) DoNothing() *StudyGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the StudyGroupCreate.OnConflict
// documentation for more info.
func (u *StudyGroupUpsertOne) Update(set func(*StudyGroupUpsert)) *StudyGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&StudyGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *StudyGroupUpsertOne) SetName(v string) *StudyGroupUpsertOne {
	return u.Update(func(s *StudyGroupUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *StudyGroupUpsertOne) UpdateName() *StudyGroupUpsertOne {
	return u.Update(func(s *StudyGroupUpsert) {
		s.UpdateName()
	})
}

// SetFacultyName sets the "facultyName" field.
func (u *StudyGroupUpsertOne) SetFacultyName(v string) *StudyGroupUpsertOne {
	return u.Update(func(s *StudyGroupUpsert) {
		s.SetFacultyName(v)
	})
}

// UpdateFacultyName sets the "facultyName" field to the value that was provided on create.
func (u *StudyGroupUpsertOne) UpdateFacultyName() *StudyGroupUpsertOne {
	return u.Update(func(s *StudyGroupUpsert) {
		s.UpdateFacultyName()
	})
}

// Exec executes the query.
func (u *StudyGroupUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for StudyGroupCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *StudyGroupUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *StudyGroupUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: StudyGroupUpsertOne.ID is not supported by MySQL driver. Use StudyGroupUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *StudyGroupUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// StudyGroupCreateBulk is the builder for creating many StudyGroup entities in bulk.
type StudyGroupCreateBulk struct {
	config
	builders []*StudyGroupCreate
	conflict []sql.ConflictOption
}

// Save creates the StudyGroup entities in the database.
func (sgcb *StudyGroupCreateBulk) Save(ctx context.Context) ([]*StudyGroup, error) {
	specs := make([]*sqlgraph.CreateSpec, len(sgcb.builders))
	nodes := make([]*StudyGroup, len(sgcb.builders))
	mutators := make([]Mutator, len(sgcb.builders))
	for i := range sgcb.builders {
		func(i int, root context.Context) {
			builder := sgcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StudyGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, sgcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = sgcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, sgcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, sgcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (sgcb *StudyGroupCreateBulk) SaveX(ctx context.Context) []*StudyGroup {
	v, err := sgcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sgcb *StudyGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := sgcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sgcb *StudyGroupCreateBulk) ExecX(ctx context.Context) {
	if err := sgcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.StudyGroup.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.StudyGroupUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (sgcb *StudyGroupCreateBulk) OnConflict(opts ...sql.ConflictOption) *StudyGroupUpsertBulk {
	sgcb.conflict = opts
	return &StudyGroupUpsertBulk{
		create: sgcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.StudyGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (sgcb *StudyGroupCreateBulk) OnConflictColumns(columns ...string) *StudyGroupUpsertBulk {
	sgcb.conflict = append(sgcb.conflict, sql.ConflictColumns(columns...))
	return &StudyGroupUpsertBulk{
		create: sgcb,
	}
}

// StudyGroupUpsertBulk is the builder for "upsert"-ing
// a bulk of StudyGroup nodes.
type StudyGroupUpsertBulk struct {
	create *StudyGroupCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.StudyGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(studygroup.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *StudyGroupUpsertBulk) UpdateNewValues() *StudyGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(studygroup.FieldID)
				return
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.StudyGroup.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *StudyGroupUpsertBulk) Ignore() *StudyGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *StudyGroupUpsertBulk) DoNothing() *StudyGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the StudyGroupCreateBulk.OnConflict
// documentation for more info.
func (u *StudyGroupUpsertBulk) Update(set func(*StudyGroupUpsert)) *StudyGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&StudyGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *StudyGroupUpsertBulk) SetName(v string) *StudyGroupUpsertBulk {
	return u.Update(func(s *StudyGroupUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *StudyGroupUpsertBulk) UpdateName() *StudyGroupUpsertBulk {
	return u.Update(func(s *StudyGroupUpsert) {
		s.UpdateName()
	})
}

// SetFacultyName sets the "facultyName" field.
func (u *StudyGroupUpsertBulk) SetFacultyName(v string) *StudyGroupUpsertBulk {
	return u.Update(func(s *StudyGroupUpsert) {
		s.SetFacultyName(v)
	})
}

// UpdateFacultyName sets the "facultyName" field to the value that was provided on create.
func (u *StudyGroupUpsertBulk) UpdateFacultyName() *StudyGroupUpsertBulk {
	return u.Update(func(s *StudyGroupUpsert) {
		s.UpdateFacultyName()
	})
}

// Exec executes the query.
func (u *StudyGroupUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the StudyGroupCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for StudyGroupCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *StudyGroupUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
