// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"tellmeac/extended-schedule/adapters/ent/predicate"
	"tellmeac/extended-schedule/adapters/ent/studygroup"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StudyGroupQuery is the builder for querying StudyGroup entities.
type StudyGroupQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.StudyGroup
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StudyGroupQuery builder.
func (sgq *StudyGroupQuery) Where(ps ...predicate.StudyGroup) *StudyGroupQuery {
	sgq.predicates = append(sgq.predicates, ps...)
	return sgq
}

// Limit adds a limit step to the query.
func (sgq *StudyGroupQuery) Limit(limit int) *StudyGroupQuery {
	sgq.limit = &limit
	return sgq
}

// Offset adds an offset step to the query.
func (sgq *StudyGroupQuery) Offset(offset int) *StudyGroupQuery {
	sgq.offset = &offset
	return sgq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sgq *StudyGroupQuery) Unique(unique bool) *StudyGroupQuery {
	sgq.unique = &unique
	return sgq
}

// Order adds an order step to the query.
func (sgq *StudyGroupQuery) Order(o ...OrderFunc) *StudyGroupQuery {
	sgq.order = append(sgq.order, o...)
	return sgq
}

// First returns the first StudyGroup entity from the query.
// Returns a *NotFoundError when no StudyGroup was found.
func (sgq *StudyGroupQuery) First(ctx context.Context) (*StudyGroup, error) {
	nodes, err := sgq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{studygroup.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sgq *StudyGroupQuery) FirstX(ctx context.Context) *StudyGroup {
	node, err := sgq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first StudyGroup ID from the query.
// Returns a *NotFoundError when no StudyGroup ID was found.
func (sgq *StudyGroupQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = sgq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{studygroup.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sgq *StudyGroupQuery) FirstIDX(ctx context.Context) string {
	id, err := sgq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single StudyGroup entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one StudyGroup entity is found.
// Returns a *NotFoundError when no StudyGroup entities are found.
func (sgq *StudyGroupQuery) Only(ctx context.Context) (*StudyGroup, error) {
	nodes, err := sgq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{studygroup.Label}
	default:
		return nil, &NotSingularError{studygroup.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sgq *StudyGroupQuery) OnlyX(ctx context.Context) *StudyGroup {
	node, err := sgq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only StudyGroup ID in the query.
// Returns a *NotSingularError when more than one StudyGroup ID is found.
// Returns a *NotFoundError when no entities are found.
func (sgq *StudyGroupQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = sgq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{studygroup.Label}
	default:
		err = &NotSingularError{studygroup.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sgq *StudyGroupQuery) OnlyIDX(ctx context.Context) string {
	id, err := sgq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of StudyGroups.
func (sgq *StudyGroupQuery) All(ctx context.Context) ([]*StudyGroup, error) {
	if err := sgq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return sgq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (sgq *StudyGroupQuery) AllX(ctx context.Context) []*StudyGroup {
	nodes, err := sgq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of StudyGroup IDs.
func (sgq *StudyGroupQuery) IDs(ctx context.Context) ([]string, error) {
	var ids []string
	if err := sgq.Select(studygroup.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sgq *StudyGroupQuery) IDsX(ctx context.Context) []string {
	ids, err := sgq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sgq *StudyGroupQuery) Count(ctx context.Context) (int, error) {
	if err := sgq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return sgq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (sgq *StudyGroupQuery) CountX(ctx context.Context) int {
	count, err := sgq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sgq *StudyGroupQuery) Exist(ctx context.Context) (bool, error) {
	if err := sgq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return sgq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (sgq *StudyGroupQuery) ExistX(ctx context.Context) bool {
	exist, err := sgq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StudyGroupQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sgq *StudyGroupQuery) Clone() *StudyGroupQuery {
	if sgq == nil {
		return nil
	}
	return &StudyGroupQuery{
		config:     sgq.config,
		limit:      sgq.limit,
		offset:     sgq.offset,
		order:      append([]OrderFunc{}, sgq.order...),
		predicates: append([]predicate.StudyGroup{}, sgq.predicates...),
		// clone intermediate query.
		sql:    sgq.sql.Clone(),
		path:   sgq.path,
		unique: sgq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.StudyGroup.Query().
//		GroupBy(studygroup.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sgq *StudyGroupQuery) GroupBy(field string, fields ...string) *StudyGroupGroupBy {
	grbuild := &StudyGroupGroupBy{config: sgq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := sgq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return sgq.sqlQuery(ctx), nil
	}
	grbuild.label = studygroup.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.StudyGroup.Query().
//		Select(studygroup.FieldName).
//		Scan(ctx, &v)
func (sgq *StudyGroupQuery) Select(fields ...string) *StudyGroupSelect {
	sgq.fields = append(sgq.fields, fields...)
	selbuild := &StudyGroupSelect{StudyGroupQuery: sgq}
	selbuild.label = studygroup.Label
	selbuild.flds, selbuild.scan = &sgq.fields, selbuild.Scan
	return selbuild
}

func (sgq *StudyGroupQuery) prepareQuery(ctx context.Context) error {
	for _, f := range sgq.fields {
		if !studygroup.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sgq.path != nil {
		prev, err := sgq.path(ctx)
		if err != nil {
			return err
		}
		sgq.sql = prev
	}
	return nil
}

func (sgq *StudyGroupQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*StudyGroup, error) {
	var (
		nodes = []*StudyGroup{}
		_spec = sgq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*StudyGroup).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &StudyGroup{config: sgq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sgq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (sgq *StudyGroupQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sgq.querySpec()
	_spec.Node.Columns = sgq.fields
	if len(sgq.fields) > 0 {
		_spec.Unique = sgq.unique != nil && *sgq.unique
	}
	return sqlgraph.CountNodes(ctx, sgq.driver, _spec)
}

func (sgq *StudyGroupQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := sgq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (sgq *StudyGroupQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   studygroup.Table,
			Columns: studygroup.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: studygroup.FieldID,
			},
		},
		From:   sgq.sql,
		Unique: true,
	}
	if unique := sgq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := sgq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, studygroup.FieldID)
		for i := range fields {
			if fields[i] != studygroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sgq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sgq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sgq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sgq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sgq *StudyGroupQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sgq.driver.Dialect())
	t1 := builder.Table(studygroup.Table)
	columns := sgq.fields
	if len(columns) == 0 {
		columns = studygroup.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sgq.sql != nil {
		selector = sgq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sgq.unique != nil && *sgq.unique {
		selector.Distinct()
	}
	for _, p := range sgq.predicates {
		p(selector)
	}
	for _, p := range sgq.order {
		p(selector)
	}
	if offset := sgq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sgq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// StudyGroupGroupBy is the group-by builder for StudyGroup entities.
type StudyGroupGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sggb *StudyGroupGroupBy) Aggregate(fns ...AggregateFunc) *StudyGroupGroupBy {
	sggb.fns = append(sggb.fns, fns...)
	return sggb
}

// Scan applies the group-by query and scans the result into the given value.
func (sggb *StudyGroupGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := sggb.path(ctx)
	if err != nil {
		return err
	}
	sggb.sql = query
	return sggb.sqlScan(ctx, v)
}

func (sggb *StudyGroupGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range sggb.fields {
		if !studygroup.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := sggb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sggb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (sggb *StudyGroupGroupBy) sqlQuery() *sql.Selector {
	selector := sggb.sql.Select()
	aggregation := make([]string, 0, len(sggb.fns))
	for _, fn := range sggb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(sggb.fields)+len(sggb.fns))
		for _, f := range sggb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(sggb.fields...)...)
}

// StudyGroupSelect is the builder for selecting fields of StudyGroup entities.
type StudyGroupSelect struct {
	*StudyGroupQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (sgs *StudyGroupSelect) Scan(ctx context.Context, v interface{}) error {
	if err := sgs.prepareQuery(ctx); err != nil {
		return err
	}
	sgs.sql = sgs.StudyGroupQuery.sqlQuery(ctx)
	return sgs.sqlScan(ctx, v)
}

func (sgs *StudyGroupSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := sgs.sql.Query()
	if err := sgs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
