// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"tellmeac/extended-schedule/adapters/ent/predicate"
	"tellmeac/extended-schedule/adapters/ent/studygroup"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StudyGroupDelete is the builder for deleting a StudyGroup entity.
type StudyGroupDelete struct {
	config
	hooks    []Hook
	mutation *StudyGroupMutation
}

// Where appends a list predicates to the StudyGroupDelete builder.
func (sgd *StudyGroupDelete) Where(ps ...predicate.StudyGroup) *StudyGroupDelete {
	sgd.mutation.Where(ps...)
	return sgd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sgd *StudyGroupDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(sgd.hooks) == 0 {
		affected, err = sgd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StudyGroupMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sgd.mutation = mutation
			affected, err = sgd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(sgd.hooks) - 1; i >= 0; i-- {
			if sgd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = sgd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sgd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (sgd *StudyGroupDelete) ExecX(ctx context.Context) int {
	n, err := sgd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sgd *StudyGroupDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: studygroup.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: studygroup.FieldID,
			},
		},
	}
	if ps := sgd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sgd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// StudyGroupDeleteOne is the builder for deleting a single StudyGroup entity.
type StudyGroupDeleteOne struct {
	sgd *StudyGroupDelete
}

// Exec executes the deletion query.
func (sgdo *StudyGroupDeleteOne) Exec(ctx context.Context) error {
	n, err := sgdo.sgd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{studygroup.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sgdo *StudyGroupDeleteOne) ExecX(ctx context.Context) {
	sgdo.sgd.ExecX(ctx)
}
