// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// StudyGroup is the predicate function for studygroup builders.
type StudyGroup func(*sql.Selector)

// Teacher is the predicate function for teacher builders.
type Teacher func(*sql.Selector)

// UserConfig is the predicate function for entuserconfig builders.
type UserConfig func(*sql.Selector)
