@startuml class_diagramm

namespace domain {
    namespace aggregate {
        class UserConfig <Aggregate> {
            +UserID uuid.UUID
            +JoinedGroups []GroupInfo
            +IgnoredLessons []ExcludedLesson
            +ExtendedLessons []ExtendedLesson
        }

    }

    namespace entity {
        class ExcludedLesson <Entity> {
            +ID uuid.UUID
            +LessonRef string
        }

        class ExtendedLesson <Entity> {
            +ID uuid.UUID
            +Author uuid.UUID
            +IsPrivate bool
            +Context *LessonContext
            +Intervals []LessonInterval
        }

        class GroupInfo <Entity> {
            + ID uuid.UUID
            + Name string
        }
    }

    domain.aggregate.UserConfig "M" o-- "1" domain.entity.ExcludedLesson
    domain.aggregate.UserConfig "M" o-- "1" domain.entity.ExtendedLesson
    domain.aggregate.UserConfig "M" o-- "1" domain.entity.GroupInfo

    namespace repository {
        interface IExcludedRepository {

        }

        interface IExtendedRepository {

        }

        interface IGroupRepository {

        }
    }

    namespace factory {
        interface IUserConfigFactory {
            +Make(userID uuid.UUID) aggregate.UserConfig
        }

        IUserConfigFactory --> domain.aggregate.UserConfig

        class userConfigFactory implements IUserConfigFactory {
            -excluded IExcludedRepository
            -extended IExtendedRepository
            -userConfig IUserConfigRepository
        }

        userConfigFactory "1" o-- "1" domain.repository.IExcludedRepository
        userConfigFactory "1" o-- "1" domain.repository.IExtendedRepository
        userConfigFactory "1" o-- "1" domain.repository.IGroupRepository
    }
}

namespace service {
    interface IService {

    }

    class service implements IService {
        -userConfigFactory IUserConfigFactory
        -excluded IExcludedRepository
        -extended IExtendedRepository
        -userConfig IUserConfigRepository
    }

    service "1" o-- "1" domain.factory.IUserConfigFactory
    service "1" o-- "1" domain.repository.IExcludedRepository
    service "1" o-- "1" domain.repository.IExtendedRepository
    service "1" o-- "1" domain.repository.IGroupRepository
}

@enduml