@startuml EntityDiagram

class UserConfig <Aggregate> {
    +UserID uuid.UUID
    +JoinedGroups []GroupInfo
    +IgnoredLessons []IgnoredLesson
    +AdditionalLessons []AdditionalLessons
}

class IgnoredLesson {
    +ID uuid.UUID
    +UserID uuid.UUID
    +LessonRef string
}

class AdditionalLesson {
    +ID uuid.UUID
    +UserID uuid.UUID
    +Context LessonContext
    +Intervals []LessonInterval
}

class GroupInfo {
    + ID uuid.UUID
    + Name string
}

UserConfig "M" o-- "1" IgnoredLesson
UserConfig "M" o-- "1" AdditionalLesson
UserConfig "M" o-- "1" GroupInfo

@enduml