@startuml EntityDiagram

entity UserJoinedGroups {
    * id: uuid <PK>
    --
    * user_id: uuid <FK>
    * joined_groups: JSON
}

entity ExcludedLesson {
    * id: uuid
    --
    * user_id: uuid <FK>
    * lesson_ref: string
}

entity ExtendedLesson {
    * id: uuid <PK>
    --
    * user_id: uuid <FK>
    * context: JSON
    * intervals JSON
}

@enduml