@startuml EntityDiagram

entity UserConfig {
    * id: uuid <PK>
    --
    * joined_groups: JSON
}

entity IgnoredLessons {
    * id: uuid
    --
    * config_id: uuid <FK>
    * lesson: string
}

IgnoredLessons --o{ UserConfig

entity ExtendedLessons {
    * id: uuid <PK>
    --
    * config_id: uuid <FK>
    * context: JSON
    * intervals JSON
}

ExtendedLessons --o{ UserConfig

@enduml