@startuml caching

class Item

interface IProvider {
    +GetAll() []Item
}

IProvider -> Item

class provider implements IProvider

class cachingProvider implements IProvider {
    -provider IProvider
}

cachingProvider "1" o-- "1" IProvider

@enduml