version: '2'

services:
  database:
    image: "postgres:14"  
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always

  schedule:
    image: "cloud.canister.io:5000/d4yw41ker/better_schedule:0.1.0"
    container_name: "schedule"
    ports:
    - "8080:8080"
    environment:
      DATABASE_CONNECTIONADDRESS: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    depends_on:
      - database
    restart: always