openapi: 3.0.0
info:
  title: TSU Schedule
  description: TSU schedule public API
  version: 0.1.0
servers:
  - url: https://intime.tsu.ru/api/web/v1
    description: Web API path

paths:
  /schedule/group:
    get:
      summary: Schedule by group
      parameters:
        - name: id
          in: query
          required: true
          description: groupd identifier
          schema:
            type: string
        - name: dateFrom
          in: query
          required: true
          description: "date to start from"
          schema:
            type: string
            example: "2020-04-11"
        - name: dateTo
          in: query
          required: true
          description: "date to end"
          schema:
            type: string
            example: "2020-04-11"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                title: "Schedule list by day"
                type: array
                items:
                  $ref: "#/components/schemas/DaySchedule"

components:
  schemas:
    DaySchedule:
      title: "Schedule for one day"