@startuml Containers

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, User, "Student or teacher")

System_Boundary(api, "Extended Schedule") {
    Container(spa, "SPA", "Vue3/TypeScript")

    Container(UserConfigService, "Settings Service", "Go", "Works with configuration")
    Container(ScheduleService, "Schedule Service", "Go", "Provides schedule")

    ContainerDb(db, "Postgres", "SQL Database", "Stores user configuration")

    Rel(ScheduleService, UserConfigService, "Uses", "gRPS")

    Rel(spa, UserConfigService, "Uses", "JSON/HTTPS")
    Rel(spa, ScheduleService, "Uses", "JSON/HTTPS")

    Rel(UserConfigService, db, "Uses")
}

System_Ext(oauth, "OAuth2 Google", "External OAuth2 provider")
System_Ext(scheduleProvider, "Schedule Source", "Base schedule provider")

Rel(user, spa, "Uses", "HTTPS")

Rel_R(UserConfigService, oauth, "Authorizes requests with", "HTTPS")
Rel_R(ScheduleService, oauth, "Authorizes requests with", "HTTPS")
Rel_R(spa, oauth, "Receives access token", "HTTPS")

Rel(ScheduleService, scheduleProvider, "Uses", "JSON/HTTPS")
Rel(UserConfigService, scheduleProvider, "Uses", "JSON/HTTPS")

@enduml
