sequenceDiagram
    API ->> ScheduleService: Get user's schedule

    ScheduleService ->> ScheduleBuilder: Build users's schedule

    ScheduleBuilder ->> UserConfigDAO: Get config
    UserConfigDAO -->> ScheduleBuilder: User's config

    ScheduleBuilder ->> BaseScheduleProvider: Get required groups schedule
    BaseScheduleProvider -->> ScheduleBuilder: Base schedule

    ScheduleBuilder ->> ScheduleBuilder: Build schedule by configuration

    ScheduleBuilder -->> ScheduleService: Builded users's schedule

    ScheduleService -->> API: User's schedule