openapi: 3.0.1
info:
  title: ScheduleService
  description: Service to provide schedule.
  version: 1.0.0
servers:
  - url: http://{hostname}/api
    variables:
      hostname:
        default: localhost
paths:
  /user/{userId}/schedule:
    get:
      summary: "Get user's specific schedule"
      responses:
        200:
          description: OK
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not found
  /schedule/byGroup/{groupId}:
    get:
      summary: "Get group's schedule"
      responses:
        200:
          description: OK
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not found
  /lessons/byGroup/{groupId}:
    get:
      summary: "Get group's lesson list"
      responses:
        200:
          description: OK
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not found
  /faculties:
    get:
      summary: "Get faculty list"
      responses:
        200:
          description: OK