openapi: 3.0.1
info:
  title: InfoService
  description: Service to lessons and faculties withing schedule context.
  version: 1.0.0

servers:
  - url: http://{hostname}/api/v1
    variables:
      hostname:
        default: localhost
paths:
  /lessons/byGroup/{groupId}:
    get:
      summary: "Get group's lesson list"
      tags:
        - Lessons
      responses:
        200:
          description: OK
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not found
  /faculties:
    get:
      summary: "Get faculty list"
      tags:
        - Faculties
      responses:
        200:
          description: OK

components:
  
  schemas:
    # TODO: define schemas below
    # Teacher
    # Lesson
    Faculty:
      properties:
        id:
          type: string
        name:
          type: string