openapi: 3.0.1
info:
  title: UserConfig
  description: Service to provide methods to work with user settings
  version: 1.0.0
servers:
  - url: http://{hostname}/api
    variables:
      hostname:
        default: localhost
paths:
  /user/{userId}/config:
    get:
      summary: "Get user configuration"
      responses:
        200:
          description: OK
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not found
    patch:
      summary: "Update user configuration"
      responses:
        200:
          description: OK
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not found
  
  