openapi: 3.0.1
info:
  title: ScheduleService
  description: Service to provide schedule.
  version: 1.0.0
servers:
  - url: http://{hostname}/api/v1
    variables:
      hostname:
        default: localhost
paths:
  /user/{id}/schedule:
    get:
      summary: "Get personal schedule"
      security:
        - bearerAuth: []
      tags:
        - Schedule
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Schedule"
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not found
  /schedule/byGroup/{id}:
    get:
      summary: "Get group's schedule"
      tags:
        - Schedule
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Schedule"
        404:
          description: Not found
  /lessons/byGroup/{id}:
    get:
      summary: "Get group's lesson list"
      tags:
        - Lessons
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Lesson"
        404:
          description: Not found
  /faculties:
    get:
      summary: "Get faculty list"
      tags:
        - Faculties
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Faculty"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Schedule:
      required:
        - startDate
        - endDate
        - days
      properties:
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        days:
          description: "ascending ordered schedule days"
          type: array
          items:
            $ref: "#/components/schemas/Day"
    Day:
      required:
        - date
        - cells
      properties:
        date:
          type: string
          format: date
        cells:
          type: array
          items:
            $ref: "#/components/schemas/Cell"
    Cell:
      required:
        - pos
        - lessons
      properties:
        pos:
          description: "Position"
          type: number
        lessons:
          nullable: true
          type: array
          items:
            $ref: "#/components/schemas/Lesson"
    Lesson:
      required:
          - id
          - name
          - kind
          - teacher
          - groups
      properties:
        id:
          type: string
        name:
          type: string
        kind:
          type: string
        teacher:
          anyOf:
            - type: 'null'
            - $ref: "#/components/schemas/Teacher"
        groups:
          description: "Study group codes"
          type: array
          items:
            type: string
    Teacher:
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
    Faculty:
      required:
          - id
          - name
      properties:
        id:
          type: string
        name:
          type: string
