// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// StudyGroupsColumns holds the columns for the "study_groups" table.
	StudyGroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "faculty_name", Type: field.TypeString},
	}
	// StudyGroupsTable holds the schema information for the "study_groups" table.
	StudyGroupsTable = &schema.Table{
		Name:       "study_groups",
		Columns:    StudyGroupsColumns,
		PrimaryKey: []*schema.Column{StudyGroupsColumns[0]},
	}
	// TeachersColumns holds the columns for the "teachers" table.
	TeachersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
	}
	// TeachersTable holds the schema information for the "teachers" table.
	TeachersTable = &schema.Table{
		Name:       "teachers",
		Columns:    TeachersColumns,
		PrimaryKey: []*schema.Column{TeachersColumns[0]},
	}
	// UserConfigsColumns holds the columns for the "user_configs" table.
	UserConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "email", Type: field.TypeString},
		{Name: "base", Type: field.TypeJSON},
		{Name: "extended_groups", Type: field.TypeJSON},
		{Name: "exclude_rules", Type: field.TypeJSON},
	}
	// UserConfigsTable holds the schema information for the "user_configs" table.
	UserConfigsTable = &schema.Table{
		Name:       "user_configs",
		Columns:    UserConfigsColumns,
		PrimaryKey: []*schema.Column{UserConfigsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "userconfig_email",
				Unique:  true,
				Columns: []*schema.Column{UserConfigsColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		StudyGroupsTable,
		TeachersTable,
		UserConfigsTable,
	}
)

func init() {
}
